version: '3'
services:
  es-service-node0:
    image: elasticsearch:6.8.6
    container_name: my-es-node0
    privileged: true
    environment:
      - cluster.name=my-elasticsearch-cluster
      - node.name=node0
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=es-service-node0,es-service-node1,es-service-node2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node0:/opt/elasticsearch/data
      - ./logs/node0:/opt/elasticsearch/logs
    ports:
      - 9200:9200
  es-service-node1:
    image: elasticsearch:6.8.6
    container_name: my-es-node1
    privileged: true
    environment:
      - cluster.name=my-elasticsearch-cluster
      - node.name=node1
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=es-service-node0,es-service-node1,es-service-node2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node1:/opt/elasticsearch/data
      - ./logs/node1:/opt/elasticsearch/logs
    ports:
      - 9201:9200
  es-service-node2:
    image: elasticsearch:6.8.6
    container_name: my-es-node2
    privileged: true
    environment:
      - cluster.name=my-elasticsearch-cluster
      - node.name=node2
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "discovery.zen.ping.unicast.hosts=es-service-node0,es-service-node1,es-service-node2"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/node2:/opt/elasticsearch/data
      - ./logs/node2:/opt/elasticsearch/logs
    ports:
      - 9202:9200
  es-service-head:
    image: mobz/elasticsearch-head:5
    container_name: my-elasticsearch-head
    volumes:
       - /opt/elasticsearch/elasticsearch-head/Gruntfile.js:/usr/src/app/Gruntfile.js
       - /opt/elasticsearch/elasticsearch-head/_site/app.js:/usr/src/app/_site/app.js        
    ports:
       - 9100:9100           
    links:
       - es-service-node0:elasticsearch